name: Lint

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://npm.pkg.github.com/
                  scope: '@university-of-york'
                  always-auth: true
                  cache: npm

            - name: Install dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Check formatting
              run: npx prettier --check .

            - name: Validate TypeScript
              run: npx tsc --noEmit

            - name: Run Linter
              run: npm run lint
