name: Run SonarQube scan

on:
    push:
        branches:
            - main

permissions:
    contents: read # on checkout
    packages: read

jobs:
    coverage:
        name: Upload code coverage to SonarQube
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://npm.pkg.github.com/
                  scope: '@university-of-york'
                  cache: npm

            - name: Install dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Run tests with coverage
              run: npm run test-coverage

            - name: Run SonarQube scan
              uses: SonarSource/sonarqube-scan-action@v4.0.0
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
                  RUNNER_DEBUG: 1
